name: ironhide
description: Use ironhide to decrypt files
inputs:
  keys:
    description: Contents of ~/.iron/keys for the service account.
    required: true
  input:
    description: Name of file to decrypt.
    required: true
runs:
  using: composite
  steps:
    - name: Download release
      uses: robinraju/release-downloader@v1.6
      with:
        repository: "IronCoreLabs/ironhide"
        fileName: "*linux-musl*"
        latest: true
        tarBall: true
    - name: Unzip and rename
      run: |
        tar -xf *linux-musl*
        rm -rf *.gz
        mv *linux-musl* ironhide
      shell: bash
    - name: Set keys and decrypt
      run: |
        mkdir -p ~/.iron
        echo '${{ inputs.keys }}' > ~/.iron/keys
        ironhide/ironhide file decrypt ${{ inputs.input }}
        ls
      shell: bash
