name: ironhide
description: Use ironhide to decrypt files
inputs:
  keys:
    description: Contents of ~/.iron/keys for the service account.
    required: true
  input:
    description: Name of file to decrypt.
    required: true
runs:
  using: composite
  steps:
    - name: Set env vars (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo FILE_PATTERN='*linux-musl*' >> $GITHUB_ENV
        echo UNZIP_CMD='tar -xf *linux-musl*' >> $GITHUB_ENV
    - name: Set env vars (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo FILE_PATTERN='*apple-darwin*' >> $GITHUB_ENV
        echo UNZIP_CMD='tar -xf *apple-darwin*' >> $GITHUB_ENV
    - name: Set env vars (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo FILE_PATTERN='*windows-gnu*' >> $GITHUB_ENV
        echo UNZIP_CMD='7z x *windows-gnu*' >> $GITHUB_ENV
    - name: Download ironhide release
      uses: robinraju/release-downloader@v1.6
      with:
        repository: "IronCoreLabs/ironhide"
        fileName: ${{ env.FILE_PATTERN }}
        latest: true
        tarBall: true
        zipBall: true
    - name: Unzip and rename
      shell: bash
      run: |
        ${{ env.UNZIP_CMD }}
        rm -rf ${{ env.FILE_PATTERN }}.gz
        rm -rf ${{ env.FILE_PATTERN }}.zip
        mv ${{ env.FILE_PATTERN }} ironhide
    - name: Set keys and decrypt
      shell: bash
      run: |
        mkdir -p ~/.iron
        echo '${{ inputs.keys }}' > ~/.iron/keys
        ironhide/ironhide file decrypt ${{ inputs.input }}
