name: ironhide
description: Use ironhide to decrypt files
inputs:
  keys:
    description: Contents of ~/.iron/keys for the service account.
    required: true
  input:
    description: Name of file to decrypt.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install -g --unsafe-perm @ironcorelabs/ironhide
      shell: bash
    - run: entrypoint.sh ${{ inputs.keys }} file:decrypt ${{ inputs.input }}
      shell: bash
